export const customInputNodes: Record<string, string> = {
  ComfyUIDeployExternalText: "string",
  ComfyUIDeployExternalTextAny: "string",
  ComfyUIDeployExternalImage: "string - (public image url)",
  ComfyUIDeployExternalImageAlpha: "string - (public image url)",
  ComfyUIDeployExternalImageBatch: "string - (public image url or batch)",
  ComfyUIDeployExternalNumber: "float",
  ComfyUIDeployExternalNumberInt: "integer",
  ComfyUIDeployExternalNumberSlider: "float",
  ComfyUIDeployExternalNumberSliderInt: "integer",
  ComfyUIDeployExternalEnum: "enum",
  ComfyUIDeployExternalBoolean: "boolean",
  ComfyUIDeployExternalSeed: "integer",
  ComfyUIDeployExternalLora: "string - (public lora download url)",
  ComfyUIDeployExternalCheckpoint: "string - (public checkpoints download url)",
  ComfyUIDeployExternalFaceModel: "string - (public face model download url)",
  ComfyUIDeployExternalAudio: "string - (public audio url)",
  ComfyUIDeployExternalEXR: "string - (public exr url)",
  ComfyUIDeployExternalFile: "string - (public file url)",
  ComfyUIDeployExternalVid: "string - (public video url)",
  ComfyUIDeployExternalVideo: "string - (public video url)",
};
